Repository Lotte-Feelmycode/the-parabole-event, pull requests merged in 2022-11, with the labels that each got.

#6 [feature/fixgradle] gradle 파일 수정 및 evententity 수정
  .gitignore
  build.gradle
  src/main/java/com/feelmycode/parabole/domain/Event.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/feelmycode/parabole/controller/EventParticipantTest.java
Labels: Feat, Fix

#10 [feature/kafka refactoring] 카프카 수정
  build.gradle
  src/main/java/com/feelmycode/parabole/controller/EventApplyController.java
  src/main/java/com/feelmycode/parabole/domain/EventParticipant.java
  src/main/java/com/feelmycode/parabole/dto/EventApplyDto.java
  src/main/java/com/feelmycode/parabole/messagequeue/KafkaConsumerConfig.java
  src/main/java/com/feelmycode/parabole/messagequeue/KafkaProducerConfig.java
  src/main/java/com/feelmycode/parabole/messagequeue/KafkaTopicConfig.java
  src/main/java/com/feelmycode/parabole/messagequeue/kafkaConsumer.java
  src/main/java/com/feelmycode/parabole/service/EventParticipantService.java
  src/main/java/com/feelmycode/parabole/service/EventWinnerService.java
  src/main/resources/data.sql
Labels: Fix

#12 [feature/jwt] 이벤트서버에 jwt 토큰 해독기 설치 & API 테스트
  build.gradle
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/global/config/JwtAuthenticationFilter.java
  src/main/java/com/feelmycode/parabole/global/util/JwtUtils.java
Labels: Feat

#16 [feature/jwthotfix] jwt API값 인식 오류 해결
  src/main/java/com/feelmycode/parabole/global/config/JwtAuthenticationFilter.java
Labels: !HOTFIX

#17 [feature/eventRestDocs] 이벤트 레스트독스 일부 수정
  src/docs/asciidoc/snippets/eventparticipant-check/curl-request.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/http-request.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/http-response.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/httpie-request.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/request-body.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/request-fields.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/response-body.adoc
  src/docs/asciidoc/snippets/eventparticipant-check/response-fields.adoc
  src/docs/asciidoc/snippets/eventparticipant/curl-request.adoc
  src/docs/asciidoc/snippets/eventparticipant/http-request.adoc
  src/docs/asciidoc/snippets/eventparticipant/http-response.adoc
  src/docs/asciidoc/snippets/eventparticipant/httpie-request.adoc
  src/docs/asciidoc/snippets/eventparticipant/request-body.adoc
  src/docs/asciidoc/snippets/eventparticipant/request-fields.adoc
  src/docs/asciidoc/snippets/eventparticipant/response-body.adoc
  src/docs/asciidoc/snippets/eventparticipant/response-fields.adoc
  src/main/java/com/feelmycode/parabole/controller/EventApplyController.java
  src/main/java/com/feelmycode/parabole/dto/EventParticipantUserDto.java
  src/main/java/com/feelmycode/parabole/dto/RequestEventApplyCheckDto.java
  src/main/java/com/feelmycode/parabole/repository/EventParticipantRepository.java
  src/main/java/com/feelmycode/parabole/service/EventParticipantService.java
  src/main/resources/application.yml
  src/test/java/com/feelmycode/parabole/controller/EventApplyControllerTest.java
  src/test/java/com/feelmycode/parabole/controller/EventParticipantTest.java
Labels: Feat, Fix

#18 [feature/fix/event] 셀러 상관없이 조회 되던 오류 수정
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/service/EventService.java
Labels: Fix

#20 [feature/participant] Response 수정
  src/main/java/com/feelmycode/parabole/dto/EventParticipantDto.java
  src/main/java/com/feelmycode/parabole/service/EventParticipantService.java
Labels: Feat

#21 Feat: 이벤트 이미지 등록 aws s3 service 이전
  build.gradle
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/dto/EventCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/service/AwsS3Service.java
Labels: Feat

#22 [feature/createEvent] LocalDateTime직렬화 안되는 오류 수정
  src/main/java/com/feelmycode/parabole/controller/EventController.java
  src/main/java/com/feelmycode/parabole/dto/EventCreateRequestDto.java
  src/main/java/com/feelmycode/parabole/service/EventService.java
Labels: Fix

#23 Fix: inputStream length를 정해주지않아서 생기는 오류 수정
  src/main/java/com/feelmycode/parabole/service/AwsS3Service.java
Labels: Fix
